id: 8be41a6b63a14282b671862c149b9576
initial_creation_type: ocr
source_metadata:
  volumes:
    e2c1f856628344f7815933fec3a88e2f:
      base_file: v004.txt
      image_group_id: I1PD95849
      title: དགོངས་པའི་སྐད་ཀྱི་འགྲེལ་པ།
      total_pages: 1678
      volume_number: 4
